USE sakila;

#1. List all customers along with their email addresses.

SELECT customer_id, first_name, last_name, email
FROM customer;

#2. Retrieve all films with a rental rate greater than 4.

SELECT film_id, title, rental_rate
FROM film
WHERE rental_rate > 4;

#3. Display the first and last names of all actors.

SELECT first_name, last_name
FROM actor;

#4. Retrieve all films released in 2006.

SELECT film_id, title, release_year 
FROM film
WHERE release_year = 2006;

#5. Show all categories in the category table.

SELECT * FROM category;

SELECT category_id, name
FROM category;

#6. Find all customers whose first name starts with 'J'.

SELECT customer_id, first_name, last_name, email
FROM customer 
WHERE first_name LIKE 'J%';

#'J%' - END WITH J
#'%J%' - MIDDLE J

#7. Retrieve all films where the title contains the word "ACTION."

SELECT film_id, title
FROM film
WHERE title LIKE '%ACTION%' ;

#8. List all films with a length between 90 and 120 minutes.

SELECT film_id, title, length 
FROM film
WHERE length BETWEEN 90 AND 120;

#9. Sort the list of stores by their IDs in descending order

SELECT * FROM store 
ORDER BY store_id DESC;

#9. Sort the list of stores by their IDs in descending order

SELECT film_id, title, length 
FROM film
ORDER BY length DESC
LIMIT 10;

#LOWEST LIMIT
SELECT film_id, title, length 
FROM film
ORDER BY length 
LIMIT 10;

#11. Count the total number of films in the database.

SELECT COUNT(*) AS total_film
FROM film;

#12. Find the average rental rate of all films.

SELECT AVG (rental_rate) AS avg_rental_rate
FROM film;

#13. Get the minimum and maximum film lengths.

SELECT 
MIN( length) AS min_film_len,
MAX( length) AS max_film_len
FROM film;

#14. Count the total number of customers in each store.

SELECT store_id, COUNT(customer_id ) AS total_customer
FROM customer
GROUP BY store_id;

#15. Calculate the total revenue generated by the rental transactions.

SELECT SUM(amount) AS total_revenue
FROM payment;
USE sakila;

#16. Group films by their rating and count how many films belong to each rating.

SELECT rating, COUNT(film_id) AS film_count
FROM film
GROUP BY rating
order by film_count;

#17. Find the total length of films in each category

SELECT c.name AS category_name, SUM(f.length) AS total_length
FROM category c
JOIN film_category fc ON fc.category_id = c.category_id
JOIN film f ON f.film_id = fc.film_id 
GROUP BY c.name
ORDER BY total_length;

#18. List the number of films available for each replacement cost

SELECT replacement_cost, COUNT(film_id) AS film_available 
FROM film 
GROUP BY replacement_cost
ORDER BY film_available;

#19. Find the average rental rate for each film category.

SELECT c.name AS category_name, AVG(f.rental_rate) AS avg_rental_rate 
FROM category c
JOIN film_category fc ON fc.category_id = c.category_id
JOIN film f ON f.film_id = fc.film_id
GROUP BY c.name
ORDER BY avg_rental_rate;

#20. Count the number of actors in each last name group.

SELECT last_name, COUNT(actor_id) AS actor_count
FROM actor
GROUP BY last_name
ORDER BY actor_count;

